### ISSUE TITLE
Portfolio Summary Errors

### ISSUE THREAD

**Issue by vkbytes** [PhracturedBlue/fava-portfolio-summary#6]
I configured the plugin as mentioned int he document but I am seeing the following error when I access the account. 

```
127.0.0.1 - - [24/Mar/2023 23:44:31] "GET /vkbytes-expenses/extension/PortfolioSummary/?interval=day&partial=true HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/fava/application.py", line 362, in extension_report
    content = Markup(render_template_string(template, extension=extension))
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/flask/templating.py", line 159, in render_template_string
    return _render(app, template, context)
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 21, in top-level template code
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/fava_portfolio_summary/__init__.py", line 53, in portfolio_accounts
    return portfolio_summary.run()
  File "/Users/vkbytes/miniforge3/lib/python3.9/site-packages/fava_portfolio_summary/__init__.py", line 85, in run
    tree = self.ledger.root_tree
AttributeError: 'FavaLedger' object has no attribute 'root_tree'

```
I am not sure of what this FavaLedger `root_tree` has to be

**Comment by PhracturedBlue** [comment]
Looks like fava may have changed its interface.  I'll look into it

**Comment by PhracturedBlue** [comment]
This is now fixed.  Thanks for the report
